### ISSUE TITLE
CSS for depth

### ISSUE THREAD

**Issue by jonathan-s** [gfranko/jquery.tocify.js#72]
You can choose to have a deeper nested structure. The default is currently two levels deep. But what I feel is missing so to be able to style the different levels depending on how deep they are. So it would be nice to have tocify to add classes for the different depth levels.

**Comment by sman591** [comment]
I solved this by separating the nav-indent and nav-padding:

```css
ul.tocify-subheader {
   margin-left: $nav-indent;
}
.tocify-subheader .tocify-item>a {
   padding-left: $nav-padding;
}
```
```js
$("#toc").tocify({
   selectors: 'h1, h2, h3',
...
```
